# Generated by Django 4.0.3 on 2022-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField()),
            ],
        ),
    ]
